###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: service-redis

    mariadb:
      image: mariadb:10.1
      container_name: service-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=services_db
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: service-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: service-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      environment:
        DATABASE_URL: mysql://root:123456@mariadb:3306/services_db

